_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 3
                - 16
                - 17
                - 23
                - 55
            "4": 3.9.20
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
ae_input_dim:
    value: 784
ae_latent_dim:
    value: 10
batch_size:
    value: 1024
divers_loss:
    value: 1
epochs:
    value: 200
grad_penalty:
    value: 100
inner_loss:
    value: 1
lr:
    value: 0.0001
n_distill:
    value: 10000
save_dir:
    value: ./checkpoints/vae
save_every:
    value: 50
sigma:
    value: 1
vae_input_dim:
    value: 784
vae_latent_dim:
    value: 10
vae_output_dim:
    value: 784
weight_decay:
    value: "1e-4"
